In [2]:
import numpy as np

In [3]:
np.arange(-10, 11)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [5]:
np.arange(0, 25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
a = np.arange(0, 101)

In [9]:
a[a % 2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [15]:
np.linspace(1, 99, 50, dtype=np.int8)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99],
      dtype=int8)

In [17]:
np.arange(0, 10.1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [18]:
np.arange(50, 100).sum()

3725

In [19]:
np.random.randint(50, size=(5, 10)).mean(axis=1)

array([32.6, 22.7, 35.5, 31.2, 24.2])

In [20]:
np.random.randint(50, size=(5, 10)).sum(axis=0)

array([103, 122, 134,  94, 115, 120, 110, 129,  65, 157])

In [24]:
b = np.random.random(10)

In [25]:
b[b > 0.5]

array([0.98000511, 0.89008388, 0.89646349, 0.86917378, 0.94151445,
       0.5235654 ])

In [32]:
hoch2 = np.arange(1, 21) ** 2
hoch2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [36]:
hoch2[hoch2 % 2 == 0]

array([  4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

In [40]:
r = np.random.randint(100, size=(100))

In [41]:
r

array([11, 80, 36, 94,  8, 24,  7, 14, 32,  0, 80, 67, 11,  0, 59, 48, 46,
       59, 20, 65, 73, 43, 96, 77, 36, 74, 34, 90, 57, 71, 91,  0, 53, 91,
       21, 55, 25, 96, 33, 75, 25, 10, 32, 77, 79, 87, 76,  2, 65, 32, 29,
       55, 81, 92, 24, 73, 72, 19,  2, 39, 46, 65,  6, 85, 50, 28, 43, 98,
       75, 27,  3, 69, 75, 21, 68, 46, 24, 99, 56, 42, 32, 55, 66,  6, 80,
       42, 52, 20, 58, 21, 40, 78, 41, 89,  4, 73, 11, 48, 72, 80])

In [48]:
r_max = r.max() * 0.8

In [49]:
r_max

79.2

In [50]:
r[r < r_max]

array([11, 36,  8, 24,  7, 14, 32,  0, 67, 11,  0, 59, 48, 46, 59, 20, 65,
       73, 43, 77, 36, 74, 34, 57, 71,  0, 53, 21, 55, 25, 33, 75, 25, 10,
       32, 77, 79, 76,  2, 65, 32, 29, 55, 24, 73, 72, 19,  2, 39, 46, 65,
        6, 50, 28, 43, 75, 27,  3, 69, 75, 21, 68, 46, 24, 56, 42, 32, 55,
       66,  6, 42, 52, 20, 58, 21, 40, 78, 41,  4, 73, 11, 48, 72])

In [53]:
 z = np.random.randint(11, size=(10, 10))

In [55]:
z.mean(axis=1) > 5

array([False,  True,  True,  True,  True, False, False, False,  True,
       False])

In [72]:
x = np.random.randint(10, size=(50))

In [73]:
y = np.random.randint(10, size=(50))

In [74]:
x - y == 0

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False])

In [75]:
x[x - y == 0]

array([7, 3, 6, 8, 1])

In [76]:
print(x)
print(y)

[7 0 0 6 5 7 5 5 8 2 5 0 7 1 3 4 2 5 4 2 2 6 5 1 0 3 2 2 2 1 0 3 8 8 0 6 5
 2 0 7 8 6 9 9 1 9 2 4 5 0]
[0 6 7 8 1 0 9 2 1 7 1 5 7 5 3 1 3 8 2 6 6 6 2 8 3 8 4 8 3 2 4 9 6 8 2 0 0
 0 1 4 7 1 3 5 1 8 7 0 8 8]


In [77]:
x == y

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False])

In [78]:
x[x == y]

array([7, 3, 6, 8, 1])