## Machine Learning

Mithilfe eines Datensets ein "Programm" generieren, welches über neue Daten Aussagen treffen kann

Normalerweise können wir ein eigenes Programm schreiben, aber manchmal gibt es Szenarien, bei denen der Aufwand dafür zu hoch ist

---

Beispiel: Wetter

08.03. 09:00 -> 7°, 9°

Wir können jetzt ein Programm schreiben, welches diese beiden Parameter nimmt und uns eine Aussage über die Temperatur trifft

Realität:

Datum, Zeit, Längengrad, Breitengrad, Niederschlag, Luftdruck, Wind, Luftfeuchtigkeit, ...

In der Realität gibt es zu viele Parameter um ein Programm per Hand zu schreiben -> Machine Learning

---

Der Machine Learning Algorithmus versucht, innerhalb von einem Datenset Zusammenhänge zu finden

Nach dem Lernprozess kommt ein Model heraus, welches neue Daten empfangen kann und eine Aussage über diese treffen kann

### Datenset

Das MAGIC Gamma Telescope Dataset

Zwei verschiedene von Partikeln die auf das Teleskop

- Gamma Strahlen
- Hadronen

Bei jedem Datensatz ist gespeichert, ob dieser sich um einen Gamma Strahl oder ein Hadron handelt

Wir können jetzt ein Machine Learning Modell schreiben, welches neue Daten klassifizieren kann

1. fLength: continuous # major axis of ellipse [mm]
2. fWidth: continuous # minor axis of ellipse [mm]
3. fSize: continuous # 10-log of sum of content of all pixels [in #phot]
4. fConc: continuous # ratio of sum of two highest pixels over fSize [ratio]
5. fConc1: continuous # ratio of highest pixel over fSize [ratio]
6. fAsym: continuous # distance from highest pixel to center, projected onto major axis [mm]
7. fM3Long: continuous # 3rd root of third moment along major axis [mm]
8. fM3Trans: continuous # 3rd root of third moment along minor axis [mm]
9. fAlpha: continuous # angle of major axis with vector to origin [deg]
10. fDist: continuous # distance from origin to center of ellipse [mm]
11. class: g,h # gamma (signal), hadron (background)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [66]:
df = pd.read_csv("Data/MAGIC.csv")

In [67]:
df

fLength    fWidth   fSize   fConc  fConc1     fAsym   fM3Long  \
0       28.7967   16.0021  2.6449  0.3918  0.1982   27.7004   22.0110   
1       31.6036   11.7235  2.5185  0.5303  0.3773   26.2722   23.8238   
2      162.0520  136.0310  4.0612  0.0374  0.0187  116.7410  -64.8580   
3       23.8172    9.5728  2.3385  0.6147  0.3922   27.2107   -6.4633   
4       75.1362   30.9205  3.1611  0.3168  0.1832   -5.5277   28.5525   
...         ...       ...     ...     ...     ...       ...       ...   
19015   21.3846   10.9170  2.6161  0.5857  0.3934   15.2618   11.5245   
19016   28.9452    6.7020  2.2672  0.5351  0.2784   37.0816   13.1853   
19017   75.4455   47.5305  3.4483  0.1417  0.0549   -9.3561   41.0562   
19018  120.5135   76.9018  3.9939  0.0944  0.0683    5.8043  -93.5224   
19019  187.1814   53.0014  3.2093  0.2876  0.1539 -167.3125 -168.4558   

       fM3Trans   fAlpha     fDist class  
0       -8.2027  40.0920   81.8828     g  
1       -9.9574   6.3609  205.2610     g  
2      -45.2160  76.9600  256.7880     g  
3       -7.1513  10.4490  116.7370     g  
4       21.8393   4.6480  356.4620     g  
...         ...      ...       ...   ...  
19015    2.8766   2.4229  106.8258     h  
19016   -2.9632  86.7975  247.4560     h  
19017   -9.4662  30.2987  256.5166     h  
19018  -63.8389  84.6874  408.3166     h  
19019   31.4755  52.7310  272.3174     h  

[19020 rows x 11 columns]

Ein Algorithmus kann mit Buchstaben nichts anfangen -> class zu 0 und 1 umwandeln

In [68]:
df["class"] == "g"

0         True
1         True
2         True
3         True
4         True
         ...  
19015    False
19016    False
19017    False
19018    False
19019    False
Name: class, Length: 19020, dtype: bool

In [69]:
df["class"] = (df["class"] == "g").astype(int)  # True und False in Python können zu 0 und 1 umgewandelt werden

In [70]:
df

fLength    fWidth   fSize   fConc  fConc1     fAsym   fM3Long  \
0       28.7967   16.0021  2.6449  0.3918  0.1982   27.7004   22.0110   
1       31.6036   11.7235  2.5185  0.5303  0.3773   26.2722   23.8238   
2      162.0520  136.0310  4.0612  0.0374  0.0187  116.7410  -64.8580   
3       23.8172    9.5728  2.3385  0.6147  0.3922   27.2107   -6.4633   
4       75.1362   30.9205  3.1611  0.3168  0.1832   -5.5277   28.5525   
...         ...       ...     ...     ...     ...       ...       ...   
19015   21.3846   10.9170  2.6161  0.5857  0.3934   15.2618   11.5245   
19016   28.9452    6.7020  2.2672  0.5351  0.2784   37.0816   13.1853   
19017   75.4455   47.5305  3.4483  0.1417  0.0549   -9.3561   41.0562   
19018  120.5135   76.9018  3.9939  0.0944  0.0683    5.8043  -93.5224   
19019  187.1814   53.0014  3.2093  0.2876  0.1539 -167.3125 -168.4558   

       fM3Trans   fAlpha     fDist  class  
0       -8.2027  40.0920   81.8828      1  
1       -9.9574   6.3609  205.2610      1  
2      -45.2160  76.9600  256.7880      1  
3       -7.1513  10.4490  116.7370      1  
4       21.8393   4.6480  356.4620      1  
...         ...      ...       ...    ...  
19015    2.8766   2.4229  106.8258      0  
19016   -2.9632  86.7975  247.4560      0  
19017   -9.4662  30.2987  256.5166      0  
19018  -63.8389  84.6874  408.3166      0  
19019   31.4755  52.7310  272.3174      0  

[19020 rows x 11 columns]

## Aufteilen des Datensets

Wir benötigen für unser Modell drei Datensets:

- Trainingsdaten
- Validierungsdaten
- Testdaten

Wir nehmen dafür das Gesamtset und teilen es in drei Teile auf

In [71]:
sample = df.sample(frac=1)  # Mischt das Datenset
sample

fLength   fWidth   fSize   fConc  fConc1    fAsym  fM3Long  fM3Trans  \
1422   37.1859  20.7287  2.7745  0.3227  0.2025 -25.4030 -28.8158  -15.4702   
4235   42.8667  20.8577  2.9540  0.2646  0.1662  21.8687  28.1173   10.4519   
15699  48.5138  33.7706  2.9582  0.1738  0.1111 -35.7116 -41.1418  -28.7975   
14730  12.8436   9.5118  2.3355  0.8176  0.5889  10.6690   9.4290   -8.5526   
3602   74.6670  18.3794  2.8987  0.2197  0.1181  23.5940  63.4413   11.7228   
...        ...      ...     ...     ...     ...      ...      ...       ...   
12133  56.5279  27.5027  3.0090  0.2449  0.1405 -59.5890  41.9594   17.7267   
8067   21.9224  20.3847  2.6656  0.3758  0.2041  13.6682   9.5162    4.1968   
18889  21.1245  15.4527  2.4183  0.4389  0.2462 -22.2253 -13.8785    5.3297   
8353   32.8552  12.6207  2.6990  0.4260  0.2850   9.0347  19.0400   10.8581   
1772   13.4506  10.3067  2.2707  0.8043  0.4102  14.8402   3.1478  -11.8820   

        fAlpha     fDist  class  
1422    5.3784  171.7160      1  
4235    6.9302  157.5590      1  
15699  72.2367  144.9764      0  
14730  54.4210  165.4330      0  
3602    7.3061  221.9510      1  
...        ...       ...    ...  
12133   6.7180  271.9720      1  
8067   63.4920  184.2140      1  
18889  88.3116  215.1870      0  
8353    5.6470  140.1990      1  
1772   45.1950  151.1860      1  

[19020 rows x 11 columns]

Trainingsdaten: 60%, Validierung: 20%, Test: 20%

In [72]:
gesamt = len(df)
trainingLen = int(gesamt * 0.6)
validLen = int(gesamt * 0.2) + trainingLen

In [73]:
training, valid, test = np.split(sample, [trainingLen, validLen])

C:\Users\lk3\source\repos\Python_DataScience_2024_03_07\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)


In [74]:
len(training)

11412

In [75]:
len(valid)

3804

In [76]:
len(test)

3804

## Standardisierung der Daten

Momentan sind unsere Daten sehr verstreut (Große Abstände zwischen den einzelnen Spalten)

In [79]:
from sklearn.preprocessing import StandardScaler

In [80]:
scaler = StandardScaler()

In [ ]:
training.columns[0:-1]  # Alle Spalten außer class

In [89]:
dataToScale = training[training.columns[0:-1]].values  # Das unterliegende Numpy Array

In [90]:
dataToScale

array([[ 3.718590e+01,  2.072870e+01,  2.774500e+00, ..., -1.547020e+01,
         5.378400e+00,  1.717160e+02],
       [ 4.286670e+01,  2.085770e+01,  2.954000e+00, ...,  1.045190e+01,
         6.930200e+00,  1.575590e+02],
       [ 4.851380e+01,  3.377060e+01,  2.958200e+00, ..., -2.879750e+01,
         7.223670e+01,  1.449764e+02],
       ...,
       [ 4.443960e+01,  1.663920e+01,  3.050200e+00, ...,  1.779700e+00,
         7.831000e+00,  1.981650e+02],
       [ 3.058070e+01,  1.270400e+01,  2.225300e+00, ..., -4.549100e+00,
         6.480000e-02,  1.293730e+02],
       [ 1.196410e+02,  3.979950e+01,  2.870100e+00, ..., -4.321900e+01,
         3.657200e+01,  3.816780e+02]])

In [91]:
scaler.fit_transform(dataToScale)

array([[-0.37808117, -0.07453098, -0.10692123, ..., -0.76485976,
        -0.85244441, -0.29641952],
       [-0.24372087, -0.0674009 ,  0.27482704, ...,  0.48036145,
        -0.79286417, -0.4856802 ],
       [-0.11015763,  0.64632002,  0.28375931, ..., -1.40506393,
         1.71453179, -0.65389321],
       ...,
       [-0.20651919, -0.30056554,  0.47941859, ...,  0.06377455,
        -0.7582786 ,  0.05716923],
       [-0.53430505, -0.51807164, -1.27492207, ..., -0.24024233,
        -1.05645625, -0.86249038],
       [ 1.57211807,  0.97954896,  0.09639428, ..., -2.09783025,
         0.34521136,  2.51049947]])

In [104]:
scaledData = scaler.fit_transform(dataToScale)

In [105]:
pd.DataFrame(scaledData)

0         1         2         3         4         5         6  \
0     -0.378081 -0.074531 -0.106921 -0.313922 -0.108219 -0.359914 -0.777098   
1     -0.243721 -0.067401  0.274827 -0.632466 -0.436267  0.444119  0.341791   
2     -0.110158  0.646320  0.283759 -1.130294 -0.934213 -0.535250 -1.019337   
3     -0.953817 -0.694511 -1.040556  2.399459  3.383728  0.253626 -0.025484   
4      0.508409 -0.204381  0.157219 -0.878639 -0.870953  0.473464  1.036003   
...         ...       ...       ...       ...       ...       ...       ...   
11407 -0.719784 -0.503408 -0.464425  0.902686  0.533417 -0.014119 -0.529818   
11408  0.494925  0.973193  0.300135  0.478874  0.373460 -0.934758 -1.399240   
11409 -0.206519 -0.300566  0.479419 -0.783788 -0.678462  0.813341 -0.664710   
11410 -0.534305 -0.518072 -1.274922  0.821542  0.616558 -0.266678 -0.473444   
11411  1.572118  0.979549  0.096394  1.244257  2.151063 -1.125824 -2.456327   

              7         8         9  
0     -0.764860 -0.852444 -0.296420  
1      0.480361 -0.792864 -0.485680  
2     -1.405064  1.714532 -0.653893  
3     -0.432559  1.030511 -0.380415  
4      0.541412 -0.778432  0.375157  
...         ...       ...       ...  
11407  0.280407  1.194209 -1.564310  
11408 -1.008408 -0.754708  1.027977  
11409  0.063775 -0.758279  0.057169  
11410 -0.240242 -1.056456 -0.862490  
11411 -2.097830  0.345211  2.510499  

[11412 rows x 10 columns]

Die Menge der class 0 und class 1 Daten ist uneben

In [97]:
training[training["class"] == 0]

fLength   fWidth   fSize   fConc  fConc1     fAsym   fM3Long  \
15699   48.5138  33.7706  2.9582  0.1738  0.1111  -35.7116  -41.1418   
14730   12.8436   9.5118  2.3355  0.8176  0.5889   10.6690    9.4290   
13162   23.8492  16.5219  2.4074  0.5284  0.3072  -25.4947  -16.4355   
17600   29.5837  24.2199  2.7604  0.2907  0.1623  -24.5701  -26.3790   
15520  142.6920  77.9510  3.3627  0.1614  0.0931  -96.1118 -179.6440   
...         ...      ...     ...     ...     ...       ...       ...   
15648  149.9170  57.9652  3.4950  0.1900  0.0984  -42.5925  -86.5879   
18323  137.8910  52.1665  3.3590  0.1654  0.1048 -185.5600  -88.8199   
13150  116.7343  76.6761  3.1593  0.2077  0.0892  -71.5037 -123.0714   
14633   74.0969  39.6845  2.9659  0.4673  0.2558  -59.2000  -60.4726   
12581  119.6410  39.7995  2.8701  0.6069  0.4525  -70.4334 -114.2610   

       fM3Trans   fAlpha     fDist  class  
15699  -28.7975  72.2367  144.9764      0  
14730   -8.5526  54.4210  165.4330      0  
13162    9.6493  13.8490  215.2110      0  
17600  -14.5909  26.5125  224.7960      0  
15520   55.4106  82.9671  231.5060      0  
...         ...      ...       ...    ...  
15648   54.4974  14.2855  276.5360      0  
18323   16.4547  30.0570  375.1990      0  
13150   58.0587  60.0177  259.1934      0  
14633  -20.5402   7.9240  270.7830      0  
12581  -43.2190  36.5720  381.6780      0  

[4005 rows x 11 columns]

In [98]:
training[training["class"] == 1]

fLength   fWidth   fSize   fConc  fConc1    fAsym  fM3Long  fM3Trans  \
1422  37.1859  20.7287  2.7745  0.3227  0.2025 -25.4030 -28.8158  -15.4702   
4235  42.8667  20.8577  2.9540  0.2646  0.1662  21.8687  28.1173   10.4519   
3602  74.6670  18.3794  2.8987  0.2197  0.1181  23.5940  63.4413   11.7228   
5932  57.0949  46.7250  3.9299  0.1334  0.0716  16.7474  53.8595   40.8924   
6336  26.6016   0.0000  2.2188  0.7915  0.4320 -27.8246 -13.8735   -0.0001   
...       ...      ...     ...     ...     ...      ...      ...       ...   
3670  26.4487  13.9988  2.5599  0.4132  0.2163  24.2044 -18.1754    9.3761   
6435  84.5970  24.7190  3.3623  0.2219  0.1335 -49.5077 -12.7191  -11.3623   
1413  22.7386  12.9693  2.6064  0.5446  0.2735  -5.0726 -16.2333    6.2894   
9562  44.4396  16.6392  3.0502  0.2370  0.1394  43.5765 -23.0971    1.7797   
373   30.5807  12.7040  2.2253  0.5298  0.2827 -19.9214 -13.3648   -4.5491   

       fAlpha     fDist  class  
1422   5.3784  171.7160      1  
4235   6.9302  157.5590      1  
3602   7.3061  221.9510      1  
5932  24.8260   78.1423      1  
6336  15.9200  189.4410      1  
...       ...       ...    ...  
3670  12.4655  153.2120      1  
6435   1.4900  279.9820      1  
1413  58.6846   76.8758      1  
9562   7.8310  198.1650      1  
373    0.0648  129.3730      1  

[7407 rows x 11 columns]

0: 4005

1: 7407

In [100]:
from imblearn.over_sampling import RandomOverSampler

In [102]:
overSampler = RandomOverSampler()

In [117]:
training[training.columns[-1]]

1422     1
4235     1
15699    0
14730    0
3602     1
        ..
1413     1
14633    0
9562     1
373      1
12581    0
Name: class, Length: 11412, dtype: int32

In [108]:
left, right = overSampler.fit_resample(scaledData, training[training.columns[-1]])  # class column wieder hinzufügen

In [109]:
left

array([[-0.37808117, -0.07453098, -0.10692123, ..., -0.76485976,
        -0.85244441, -0.29641952],
       [-0.24372087, -0.0674009 ,  0.27482704, ...,  0.48036145,
        -0.79286417, -0.4856802 ],
       [-0.11015763,  0.64632002,  0.28375931, ..., -1.40506393,
         1.71453179, -0.65389321],
       ...,
       [-0.65933951, -0.69039847, -0.85935877, ...,  0.23898969,
         0.36738022, -0.81123077],
       [-0.12168072, -0.24844411, -0.72154658, ..., -0.21926455,
         1.21152451, -0.69484688],
       [ 0.66303848,  0.47570662,  0.42135883, ...,  1.05136826,
         0.15102846,  1.78569534]])

In [110]:
right

0        1
1        1
2        0
3        0
4        1
        ..
14809    0
14810    0
14811    0
14812    0
14813    0
Name: class, Length: 14814, dtype: int32

In [114]:
data = np.hstack((left, right.values.reshape(-1, 1)))

In [115]:
pd.DataFrame(data)

0         1         2         3         4         5         6   \
0     -0.378081 -0.074531 -0.106921 -0.313922 -0.108219 -0.359914 -0.777098   
1     -0.243721 -0.067401  0.274827 -0.632466 -0.436267  0.444119  0.341791   
2     -0.110158  0.646320  0.283759 -1.130294 -0.934213 -0.535250 -1.019337   
3     -0.953817 -0.694511 -1.040556  2.399459  3.383728  0.253626 -0.025484   
4      0.508409 -0.204381  0.157219 -0.878639 -0.870953  0.473464  1.036003   
...         ...       ...       ...       ...       ...       ...       ...   
14809  1.316718  0.310593  1.154656 -0.729510 -0.655869 -1.832921  1.277871   
14810 -0.855762 -0.612244 -0.783434  1.367618  1.237409  0.012796 -0.051951   
14811 -0.659340 -0.690398 -0.859359  0.807287  0.462927 -0.186144  0.229403   
14812 -0.121681 -0.248444 -0.721547  0.278756  0.123131  0.730545  0.313749   
14813  0.663038  0.475707  0.421359 -0.865480 -0.938732 -0.602645  0.538708   

             7         8         9    10  
0     -0.764860 -0.852444 -0.296420  1.0  
1      0.480361 -0.792864 -0.485680  1.0  
2     -1.405064  1.714532 -0.653893  0.0  
3     -0.432559  1.030511 -0.380415  0.0  
4      0.541412 -0.778432  0.375157  1.0  
...         ...       ...       ...  ...  
14809 -1.110016 -0.065784  1.717384  0.0  
14810 -0.360455  1.067830 -1.370460  0.0  
14811  0.238990  0.367380 -0.811231  0.0  
14812 -0.219265  1.211525 -0.694847  0.0  
14813  1.051368  0.151028  1.785695  0.0  

[14814 rows x 11 columns]

In [125]:
len(data[data[:, -1] == 0])

7407

In [126]:
len(data[data[:, -1] == 1])

7407

Die anderen beiden Datensets müssen jetzt auch skaliert werden (aber nicht Oversampled)

Dafür können wir eine Funktion erstellen

In [131]:
def scaleDataset(data, oversample):
    left = data[data.columns[0:-1]].values
    right = data[data.columns[-1]].values

    scaler = StandardScaler()
    left = scaler.fit_transform(left)

    if oversample:
        overSampler = RandomOverSampler()
        left, right = overSampler.fit_resample(left, right)

    data = np.hstack((left, right.reshape(-1, 1)))

    return data, left, right

In [132]:
training, left_train, right_train = scaleDataset(training, oversample=True)
valid, left_valid, right_valid = scaleDataset(valid, oversample=False)
test, left_test, right_test = scaleDataset(test, oversample=False)

In [133]:
training

array([[-0.37808117, -0.07453098, -0.10692123, ..., -0.85244441,
        -0.29641952,  1.        ],
       [-0.24372087, -0.0674009 ,  0.27482704, ..., -0.79286417,
        -0.4856802 ,  1.        ],
       [-0.11015763,  0.64632002,  0.28375931, ...,  1.71453179,
        -0.65389321,  0.        ],
       ...,
       [-0.68624326, -0.32564241, -0.39934679, ...,  1.4614559 ,
         0.17530308,  0.        ],
       [-0.70370527, -0.92313199, -0.64073079, ...,  2.36802545,
        -1.4445609 ,  0.        ],
       [ 4.41303611,  3.64788434,  1.65103487, ..., -0.37237771,
         1.19376273,  0.        ]])

In [134]:
valid

array([[ 0.56898182,  0.59151229,  0.3760862 , ..., -0.78520124,
         1.17760205,  1.        ],
       [-0.8031726 , -0.8440207 , -0.95501138, ..., -0.3233675 ,
        -1.52506638,  0.        ],
       [-0.76713209, -0.68054739, -0.97250363, ...,  2.13578566,
        -1.11203153,  1.        ],
       ...,
       [ 1.3149673 ,  1.34450063,  3.08022061, ..., -0.97874719,
         0.16497526,  1.        ],
       [ 0.80704638,  0.44368265,  0.63193681, ..., -0.75627236,
         2.35027185,  1.        ],
       [-0.7633029 , -0.83601851, -1.66818968, ..., -0.73367359,
        -0.15855484,  1.        ]])

In [135]:
test

array([[-0.59122174, -0.69316444, -0.88958395, ...,  2.25054747,
        -2.12323169,  1.        ],
       [ 0.09743889, -0.1899018 , -0.23361177, ..., -0.99446474,
        -0.20377464,  1.        ],
       [ 2.65503934,  5.00974302,  3.57370604, ..., -0.47297258,
        -0.27684026,  0.        ],
       ...,
       [-0.75816545, -0.36267076, -0.84876883, ...,  2.32526491,
         0.29284554,  0.        ],
       [-0.47927531, -0.50872936, -0.26124046, ..., -0.8285786 ,
        -0.71600081,  1.        ],
       [-0.94060768, -0.62807244, -1.15770787, ...,  0.68026803,
        -0.56818789,  1.        ]])

## Verschiedene vordefinierte Modelle

kNN (k-nearest neighbors):

- Sucht die k nähesten Datenpunkte und klassifiziert den gesuchten Datenpunkt anhand der Mehrheit der Nachbarklassen
- k muss ungerade sein (3, 5, 7, 9, ...)

In [138]:
from sklearn.neighbors import KNeighborsClassifier

In [140]:
knn = KNeighborsClassifier(n_neighbors=5)

In [141]:
knn.fit(left_train, right_train)

KNeighborsClassifier()

In [143]:
knn_prediction = knn.predict(left_test)

In [144]:
knn_prediction == right_test

array([False,  True,  True, ...,  True,  True,  True])

In [168]:
def comparePrediction(prediction):
    x = prediction == right_test

    summe = len(x)
    t = len(x[x == True])
    f = len(x[x == False])
    
    print(f"Richtig: {t}")
    print(f"Falsch: {f}")
    print(f"%: {f / summe * 100}")
    print(f"%: {100 - (f / summe * 100)}")

In [169]:
comparePrediction(knn_prediction)

Richtig: 3108
Falsch: 696
%: 18.29652996845426
%: 81.70347003154575


## Naive Bayes
- Berechnet Wahrscheinlichkeiten pro Datenpunkt und vergleicht diese mit 50%

In [170]:
from sklearn.naive_bayes import GaussianNB

In [171]:
nb = GaussianNB()

In [172]:
nb.fit(left_train, right_train)

GaussianNB()

In [173]:
nb_prediction = nb.predict(left_test)

In [174]:
comparePrediction(nb_prediction)

Richtig: 2847
Falsch: 957
%: 25.157728706624603
%: 74.8422712933754


## Logistische Regression

- Datenpunkte werden bei Y=0 und Y=1 platziert
- Danach wird eine S-Kurve berechnet und geschaut ob der neue Datenpunkt über oder unter einem gewissen Wert liegt

In [175]:
from sklearn.linear_model import LogisticRegression

In [176]:
lr = LogisticRegression()

In [177]:
lr.fit(left_train, right_train)

LogisticRegression()

In [178]:
lr_prediction = lr.predict(left_test)

In [179]:
comparePrediction(lr_prediction)

Richtig: 2997
Falsch: 807
%: 21.214511041009466
%: 78.78548895899053


## Support Vector Machines
- H = Hyperplane, M = Margin
- Suche den weitesten Abstand von allen Punkten um die Hyperplane zu platzieren
- Margin ausbreiten, um nicht klassifizierte Punkte zu klassifizieren

In [180]:
from sklearn.svm import SVC

In [181]:
svc = SVC()

In [182]:
svc.fit(left_train, right_train)

SVC()

In [185]:
svc_prediction = svc.predict(left_test)

In [186]:
comparePrediction(svc_prediction)

Richtig: 3305
Falsch: 499
%: 13.117770767613038
%: 86.88222923238696


## Neurales Netzwerk

Wir können jetzt ein eigenes Model erstellen

Es gibt verschiedene Begriffe:
- Neuron: Nimmt beliebig viele Daten auf, und verarbeitet diese mithilfe der Activation Function. Bei einem Neuralen Netzwerk werden diese Neuronen miteinander verknüpft um am Ende das Machine Learning Modell zu bekommen
- Activation Function: Werden verwendet, um in dem Datenset Zusammenhänge zu finden
- Beliebt sind ReLU, Sigmoid
    - Rectified Linear Unit: Günstige Funktion (Rechenaufwand)
    - Sigmoid: Gibt einen Wert zw. 0 und 1, wird generell für die letzte Node verwendet

In [187]:
import tensorflow as tf

Keras: Werkzeug, welches das Erstellen von Modellen stark vereinfacht

In [189]:
model = tf.keras.Sequential([
        tf.keras.layers.Dense(4, activation="relu", input_shape=(10, )),  # input_shape: Form der Daten (hier 10xZeilen)
        tf.keras.layers.Dense(1, activation="sigmoid")
    ])

In [193]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),  # Adam optimization is a stochastic gradient descent method that is based on adaptive estimation of first-order and second-order moments.
              loss="binary_crossentropy",
              metrics=["accuracy"])  # Binäre Klassifizierung

In [194]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 4)                 44        
                                                                 
 dense_3 (Dense)             (None, 1)                 5         
                                                                 
Total params: 49 (196.00 Byte)
Trainable params: 49 (196.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [196]:
history = model.fit(left_train, right_train,
          epochs=100,  # Anzahl Durchläufe
          batch_size=8,  # Parallelisierung
          verbose=1)  # Outputs anzeigen

Epoch 1/100


1852/1852 [==============================] - 3s 1ms/step - loss: 0.6068 - accuracy: 0.6835
Epoch 2/100
1852/1852 [==============================] - 2s 1ms/step - loss: 0.4917 - accuracy: 0.7876
Epoch 3/100
1852/1852 [==============================] - 2s 1ms/step - loss: 0.4651 - accuracy: 0.8004
Epoch 4/100
1852/1852 [==============================] - 2s 1ms/step - loss: 0.4475 - accuracy: 0.8090
Epoch 5/100
1852/1852 [==============================] - 2s 1ms/step - loss: 0.4336 - accuracy: 0.8147
Epoch 6/100
1852/1852 [==============================] - 2s 1ms/step - loss: 0.4225 - accuracy: 0.8193
Epoch 7/100
1852/1852 [==============================] - 2s 1ms/step - loss: 0.4139 - accuracy: 0.8237
Epoch 8/100
1852/1852 [==============================] - 2s 1ms/step - loss: 0.4069 - accuracy: 0.8242
Epoch 9/100
1852/1852 [==============================] - 2s 1ms/step - loss: 0.4017 - accuracy: 0.8240
Epoch 10/100
1852/1852 [==============================] - 2s 1ms/step -

In [205]:
nn_prediction = model.predict(left_test)

119/119 [==============================] - 0s 1ms/step


In [206]:
nn_prediction >= 0.5

array([[False],
       [ True],
       [False],
       ...,
       [False],
       [ True],
       [False]])

In [215]:
comparePrediction((nn_prediction >= 0.5).reshape(-1,) == right_test)

Richtig: 2409
Falsch: 1395
%: 36.67192429022082
%: 63.32807570977918


In [219]:
# model.save("Model1.keras")

In [217]:
# model  = tf.keras.saving.load_model("Model1.keras")

In [220]:
model = tf.keras.Sequential([
        tf.keras.layers.Dense(32, activation="relu", input_shape=(10, )),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(1, activation="sigmoid")
    ])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),  # Adam optimization is a stochastic gradient descent method that is based on adaptive estimation of first-order and second-order moments.
              loss="binary_crossentropy",
              metrics=["accuracy"])  # Binäre Klassifizierung

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 32)                352       
                                                                 
 dense_5 (Dense)             (None, 32)                1056      
                                                                 
 dense_6 (Dense)             (None, 32)                1056      
                                                                 
 dense_7 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2497 (9.75 KB)
Trainable params: 2497 (9.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [221]:
history = model.fit(left_train, right_train,
          epochs=20,  # Anzahl Durchläufe
          batch_size=8,  # Parallelisierung
          verbose=1)  # Outputs anzeigen

Epoch 1/20
1852/1852 [==============================] - 3s 1ms/step - loss: 0.4069 - accuracy: 0.8129
Epoch 2/20
1852/1852 [==============================] - 2s 1ms/step - loss: 0.3529 - accuracy: 0.8424
Epoch 3/20
1852/1852 [==============================] - 2s 1ms/step - loss: 0.3411 - accuracy: 0.8490
Epoch 4/20
1852/1852 [==============================] - 2s 1ms/step - loss: 0.3335 - accuracy: 0.8493
Epoch 5/20
1852/1852 [==============================] - 2s 1ms/step - loss: 0.3300 - accuracy: 0.8512
Epoch 6/20
1852/1852 [==============================] - 2s 1ms/step - loss: 0.3244 - accuracy: 0.8541
Epoch 7/20
1852/1852 [==============================] - 2s 1ms/step - loss: 0.3221 - accuracy: 0.8557
Epoch 8/20
1852/1852 [==============================] - 2s 1ms/step - loss: 0.3175 - accuracy: 0.8561
Epoch 9/20
1852/1852 [==============================] - 2s 1ms/step - loss: 0.3147 - accuracy: 0.8561
Epoch 10/20
1852/1852 [==============================] - 2s 1ms/step - loss: 0.311

In [222]:
nn_prediction = model.predict(left_test)

119/119 [==============================] - 0s 1ms/step


In [223]:
comparePrediction((nn_prediction >= 0.5).reshape(-1,) == right_test)

Richtig: 2422
Falsch: 1382
%: 36.33017875920084
%: 63.66982124079916


In [224]:
model = tf.keras.Sequential([
        tf.keras.layers.Dense(32, activation="relu", input_shape=(10, )),
        tf.keras.layers.Dropout(0.2),  # Dropout: Wirft eine bestimmte Prozentzahl an Daten bei jedem Durchgang weg
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(1, activation="sigmoid")
    ])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),  # Adam optimization is a stochastic gradient descent method that is based on adaptive estimation of first-order and second-order moments.
              loss="binary_crossentropy",
              metrics=["accuracy"])  # Binäre Klassifizierung

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 32)                352       
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense_9 (Dense)             (None, 32)                1056      
                                                                 
 dropout_1 (Dropout)         (None, 32)                0         
                                                                 
 dense_10 (Dense)            (None, 32)                1056      
                                                                 
 dense_11 (Dense)            (None, 1)                 33        
                                                                 
Total params: 2497 (9.75 KB)
Trainable params: 2497 (9

In [225]:
history = model.fit(left_train, right_train,
          epochs=30,  # Anzahl Durchläufe
          batch_size=16,  # Parallelisierung
          verbose=1)  # Outputs anzeigen

Epoch 1/30
926/926 [==============================] - 2s 1ms/step - loss: 0.4918 - accuracy: 0.7566
Epoch 2/30
926/926 [==============================] - 1s 1ms/step - loss: 0.4210 - accuracy: 0.8032
Epoch 3/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3955 - accuracy: 0.8170
Epoch 4/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3829 - accuracy: 0.8276
Epoch 5/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3756 - accuracy: 0.8314
Epoch 6/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3622 - accuracy: 0.8358
Epoch 7/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3623 - accuracy: 0.8380
Epoch 8/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3537 - accuracy: 0.8412
Epoch 9/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3534 - accuracy: 0.8429
Epoch 10/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3513 - accuracy: 0.8420

In [226]:
nn_prediction = model.predict(left_test)

119/119 [==============================] - 0s 999us/step


In [227]:
comparePrediction((nn_prediction >= 0.5).reshape(-1,) == right_test)

Richtig: 2579
Falsch: 1225
%: 32.202944269190326
%: 67.79705573080967


In [228]:
model = tf.keras.Sequential([
        tf.keras.layers.Dense(32, activation="relu", input_shape=(10, )),
        tf.keras.layers.Dropout(0.2),  # Dropout: Wirft eine bestimmte Prozentzahl an Daten bei jedem Durchgang weg
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(1, activation="sigmoid")
    ])

model.compile(optimizer=tf.keras.optimizers.Adam(0.01),  # Adam optimization is a stochastic gradient descent method that is based on adaptive estimation of first-order and second-order moments.
              loss="binary_crossentropy",
              metrics=["accuracy"])  # Binäre Klassifizierung

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 32)                352       
                                                                 
 dropout_2 (Dropout)         (None, 32)                0         
                                                                 
 dense_13 (Dense)            (None, 32)                1056      
                                                                 
 dropout_3 (Dropout)         (None, 32)                0         
                                                                 
 dense_14 (Dense)            (None, 32)                1056      
                                                                 
 dense_15 (Dense)            (None, 1)                 33        
                                                                 
Total params: 2497 (9.75 KB)
Trainable params: 2497 (9

In [229]:
history = model.fit(left_train, right_train,
          epochs=30,  # Anzahl Durchläufe
          batch_size=16,  # Parallelisierung
          verbose=1)  # Outputs anzeigen

Epoch 1/30
926/926 [==============================] - 2s 1ms/step - loss: 0.4310 - accuracy: 0.8026
Epoch 2/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3884 - accuracy: 0.8264
Epoch 3/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3785 - accuracy: 0.8269
Epoch 4/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3780 - accuracy: 0.8275
Epoch 5/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3713 - accuracy: 0.8350
Epoch 6/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3663 - accuracy: 0.8373
Epoch 7/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3647 - accuracy: 0.8392
Epoch 8/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3597 - accuracy: 0.8382
Epoch 9/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3578 - accuracy: 0.8420
Epoch 10/30
926/926 [==============================] - 1s 1ms/step - loss: 0.3631 - accuracy: 0.8385

In [230]:
nn_prediction = model.predict(left_test)
comparePrediction((nn_prediction >= 0.5).reshape(-1,) == right_test)

119/119 [==============================] - 0s 1ms/step
Richtig: 2615
Falsch: 1189
%: 31.25657202944269
%: 68.7434279705573


In [231]:
model = tf.keras.Sequential([
        tf.keras.layers.Dense(32, activation="relu", input_shape=(10, )),
        tf.keras.layers.Dropout(0.2),  # Dropout: Wirft eine bestimmte Prozentzahl an Daten bei jedem Durchgang weg
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(1, activation="sigmoid")
    ])

model.compile(optimizer=tf.keras.optimizers.Adam(0.01),  # Adam optimization is a stochastic gradient descent method that is based on adaptive estimation of first-order and second-order moments.
              loss="binary_crossentropy",
              metrics=["accuracy"])  # Binäre Klassifizierung

In [232]:
history = model.fit(left_train, right_train,
          epochs=50,  # Anzahl Durchläufe
          batch_size=16,  # Parallelisierung
          verbose=1)  # Outputs anzeigen

Epoch 1/50
926/926 [==============================] - 2s 1ms/step - loss: 0.4490 - accuracy: 0.7900
Epoch 2/50
926/926 [==============================] - 1s 2ms/step - loss: 0.3982 - accuracy: 0.8223
Epoch 3/50
926/926 [==============================] - 1s 2ms/step - loss: 0.3910 - accuracy: 0.8267
Epoch 4/50
926/926 [==============================] - 2s 2ms/step - loss: 0.3841 - accuracy: 0.8294
Epoch 5/50
926/926 [==============================] - 1s 1ms/step - loss: 0.3787 - accuracy: 0.8306
Epoch 6/50
926/926 [==============================] - 1s 1ms/step - loss: 0.3813 - accuracy: 0.8259
Epoch 7/50
926/926 [==============================] - 1s 1ms/step - loss: 0.3745 - accuracy: 0.8294
Epoch 8/50
926/926 [==============================] - 1s 2ms/step - loss: 0.3704 - accuracy: 0.8335
Epoch 9/50
926/926 [==============================] - 1s 1ms/step - loss: 0.3691 - accuracy: 0.8350
Epoch 10/50
926/926 [==============================] - 1s 1ms/step - loss: 0.3714 - accuracy: 0.8335

In [233]:
nn_prediction = model.predict(left_test)
comparePrediction((nn_prediction >= 0.5).reshape(-1,) == right_test)

119/119 [==============================] - 0s 1ms/step
Richtig: 2639
Falsch: 1165
%: 30.625657202944268
%: 69.37434279705573
